[package]
name = "linkdoc"
version = "0.2.0"
authors = ["Wilfred Hughes <me@wilfred.me.uk>"]

[dependencies]
hyper = "0.5.0"
html5ever = "*"
tendril = "*"

[dependencies.url]
git = "https://github.com/servo/rust-url"
