[package]
name = "linkdoc"
version = "0.2.0"
authors = ["Wilfred Hughes <me@wilfred.me.uk>"]
edition = "2021"

[dependencies]
reqwest = "0.9.22"
scraper = "0.17.1"
url = "2.4.1"
colored = "2.0.4"
clap = "2.33"
crossbeam-channel = "0.4.0"
crossbeam-utils = "0.7.0"
