on: [push, pull_request]

name: Continuous integration

jobs:
  test_linux:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.72.0
      - run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.72.0
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check
